management:
  endpoints:
    web:
      exposure:
        include: "prometheus,metrics"
spring:
  flyway:
    enabled: false
    check-location: false
    baselineOnMigrate: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:postgresql://postgres:5432/hapi_fhir'
    username: postgres
    password: mysecretpassword
    driverClassName: org.postgresql.Driver
    max-active: 15
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  batch:
    job:
      enabled: false

hapi:
  fhir:
    use_apache_address_strategy: true
    use_apache_address_strategy_https: true
    subscription:
      resthook_enabled: true
    fhir_version: R4
    allow_cascading_deletes: true  # This should be disabled by default for all production instances
    allow_multiple_delete: true  # This should be disabled by default for all production instances
    delete_expunge_enabled: true  # This should be disabled by default for all production instances
    expunge_enabled: true  # This should be disabled by default for all production instances
    cors:
      allow_Credentials: true
      allowed_origin:
        - '*'
    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200
    tester:
      home:
        name: Local Tester
        server_address: 'http://localhost:8080/fhir'
        refuse_to_fetch_third_party_urls: false
        fhir_version: R4
        validation:
          requests_enabled: true
          responses_enabled: true
    validation:
      requests_enabled: false
      responses_enabled: false
keycloak:
  enabled: false